/**
 * Created by Elf on 04.09.2016.
 */
export const CMD_DETECT_DEVICE_LOCATION = 'CMD_DETECT_DEVICE_LOCATION';
export const CMD_GET_LOCATIONS_FROM_DB = 'CMD_GET_LOCATIONS_FROM_DB';
export const DEVICE_LOCATION_DETECTED = 'DEVICE_LOCATION_DETECTED';
export const SAVED_LOCATIONS_FETCHED = 'SAVED_LOCATIONS_FETCHED';

export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const ADD_LOCATION = 'SAVE_LOCATION';
export const SAVE_LOCATIONS_TO_DB = 'SAVE_LOCATIONS_TO_DB';
